name: Construire et déployer l'application Python sur Azure Web App - co2app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Récupérer le dépôt
      uses: actions/checkout@v2

    - name: Configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Exécuter pytest
      run: pytest ./test_app.py

    - name: Configurer Docker Buildx  gestion plus efficace du cache de build, builds en parallèle pour différentes étapes, builds incrémentiels, ce qui signifie que seules les parties de l'image qui ont été modifiées seront reconstruites
      uses: docker/setup-buildx-action@v1

    - name: Se connecter au registre de conteneurs Azure
      uses: docker/login-action@v1 
      with:
        registry: appco2.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Construire et pousser l'image Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: appco2.azurecr.io/co2app:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'co2seattle'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_01C9B7078B3240EA85F44D478BA3FFC7 }}
        images: |
          appco2.azurecr.io/co2app:latest
